### ISSUE TITLE
Missing input components

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas-UI#63]
There are a few missing components that I would like to see implemented.

- [x] Chip component. Used in Architect for variables attached to a prompt. Will be useful in server, too.
- [x] Range selector - https://material.io/design/components/sliders.html
- [x] Text input with a dedicated title in addition to a label. See #62
- [x] Buttons with different sizes and all color variations.
- [x] An icon that represents an edge. Used in Architect and NC in a legend to show the meaning of a given edge type.
- [x] A date picker: https://react-select.com/advanced (bottom example). Alternative full screen chooser. Alternative IOS style wheel.
- [x] Visual Analog Scale (See https://github.com/codaco/Network-Canvas/issues/913)
- [x] Relative date picker: https://github.com/codaco/Network-Canvas-UI/issues/115
- [x] Text area: https://github.com/codaco/Network-Canvas-UI/issues/114

**Comment by jthrilly** [comment]
A date picker: https://react-select.com/advanced (bottom example
